Repository andela/octopus-bn-backend, pull requests merged in 2020-03, with the labels that each got.

#35 #171516902 refactoring the search functionality
  locales/en.js
  locales/en.json
  src/controllers/tripsController.js
  src/middlewares/paramsValidator.js
  src/routes/api/trips.routes.js
  src/tests/search.test.js
  src/tests/tripRequests.test.js
Labels: ready for review

#36 #170947458 Travel Admins should be able to create accommodation
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/migrations/20200228101558-create-accommodations.js
  src/database/migrations/20200228144651-create-rooms.js
  src/database/models/Accommodations.js
  src/database/models/Rooms.js
  src/database/seeders/20200211104632-dummy-users.js
  src/database/seeders/20200226101909-dummy-accommodations.js
  src/middlewares/accommodationValidator.js
  src/middlewares/isTravelAdministrator.js
  src/middlewares/roomsValidator.js
  src/middlewares/validateAccommodationAndRoom.js
  src/routes/api/accommodation.routes.js
  src/routes/api/index.js
  src/tests/accommodation.test.js
  src/tests/mock/accommodationMock.js
  src/tests/mock/roomsMock.js
  src/tests/rooms.test.js
Labels: ready for review

#34 #170947443 Build new trip request notification feature
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/controllers/notification.js
  src/controllers/tripsController.js
  src/database/migrations/20200222121847-update-users-table.js
  src/database/migrations/20200224160513-create-notification.js
  src/database/models/notification.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/database/seeders/20200211104634-dummy-notifications.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/notification.routes.js
  src/tests/mock/notMock.js
  src/tests/notification.test.js
  src/tests/rejectTrip.test.js
  src/tests/signin.test.js
  src/tests/tripRequests.test.js
  src/utils/emailHelper.js
  src/utils/socket.js
  src/validation/user.validation.js
  views/notification.ejs
Labels: ready for review

#41 #171653861 Fix notification for new trip request
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  public/index.html
  src/controllers/tripsController.js
  src/database/seeders/20200226101607-dummy-trip-requests.js
  src/index.js
  src/routes/api/notification.routes.js
  src/routes/api/trips.routes.js
  src/tests/tripRequests.test.js
  src/utils/emailHelper.js
Labels: ready for review

#44 #170947451 delete comment
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/commentsController.js
  src/database/seeders/20200226101999-dummy-comment.js
  src/routes/api/comment.routes.js
  src/services/tripsService.js
  src/tests/delete.comment.test.js
  src/tests/rejectTrip.test.js
Labels: ready for review

#40 #170947463 Book accommodation
  .gitignore
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/migrations/20200216110620-create-travel-requests.js
  src/database/migrations/20200305072807-create-booking.js
  src/database/models/Accommodations.js
  src/database/models/Rooms.js
  src/database/models/booking.js
  src/database/models/travelRequests.js
  src/database/models/users.js
  src/database/seeders/20200226101607-dummy-trip-requests.js
  src/database/seeders/20200226101909-dummy-accommodations.js
  src/database/seeders/20200306100854-dummy-rooms.js
  src/middlewares/paramsValidator.js
  src/middlewares/validateBooking.js
  src/routes/api/accommodation.routes.js
  src/services/bookingService.js
  src/tests/bookAccomondation.test.js
  src/tests/mock/bookAccomondation.js
  src/tests/mock/tripRequestsReturnMock.js.js
  src/tests/tripRequests.test.js
Labels: ready, ready for review

#43 #170947454 Users should edit travel requests that are still "Open"
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/tripsController.js
  src/database/seeders/20200226101607-dummy-trip-requests.js
  src/middlewares/validateTrip.js
  src/routes/api/trips.routes.js
  src/tests/editTripRequest.test.js
  src/tests/mock/editTripRequestMock.js
  src/utils/objectPropertyExcluder.js
Labels: ready, ready for review

#46 #170947465 add feedback to an accommodation
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/migrations/20200310110818-create-feedbacks.js
  src/database/models/feedbacks.js
  src/middlewares/idValidator.js
  src/middlewares/validateFeedback.js
  src/routes/api/accommodation.routes.js
  src/tests/mock/tripRequestsReturnMock.js.js
  src/tests/provide.feedback.test.js
Labels: ready, ready for review

#38 #170947450 Notification for approved/rejected request
  locales/en.js
  locales/en.json
  public/index.html
  src/controllers/notification.js
  src/controllers/tripsController.js
  src/database/seeders/20200211104631-dummy-user.js
  src/index.js
  src/tests/notification.test.js
  src/utils/emailHelper.js
Labels: ready, ready for review

#49 #171749300 Refactor mark all notifications as read
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/notification.js
  src/database/seeders/20200211104634-dummy-notifications.js
  src/middlewares/unreadNotifications.js
  src/routes/api/notification.routes.js
  src/tests/markAsRead.test.js
Labels: ready, ready for review

#51 #170947455 Notifications for edited requests
  public/index.html
  src/controllers/notification.js
  src/controllers/tripsController.js
Labels: ready, ready for review

#48 #170947466 Users should be able to rate a centre
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/config/config.js
  src/database/migrations/20200311052009-create-ratings.js
  src/database/models/ratings.js
  src/middlewares/validateRating.js
  src/routes/api/accommodation.routes.js
  src/tests/accommodations.rate.test.js
  src/tests/tripRequests.test.js
Labels: ready, ready for review

#45 #170947469 chat on Barefoot Nomad
  package.json
  public/chat.html
  src/database/migrations/20200308054908-create-chats.js
  src/database/models/chats.js
  src/database/seeders/20200211104632-dummy-users.js
  src/index.js
  src/routes/api/chat.routes.js
  src/routes/api/index.js
  src/tests/chat.test.js
  src/utils/socket.js
  views/index.ejs
Labels: ready, ready for review

#53 #170947467 Trip requests statistics
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/tripsController.js
  src/routes/api/trips.routes.js
  src/services/tripsService.js
  src/tests/tripStats.test.js
  src/validation/validateStatsDate.js
Labels: ready

#50 #170947464 Build like/unlike feature
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/controllers/notification.js
  src/database/migrations/20200311060335-create-acommodation-likes-and-unlikes.js
  src/database/models/acommodationlikesandunlikes.js
  src/middlewares/isAccomodation.js
  src/routes/api/accommodation.routes.js
  src/services/accomodationService.js
  src/utils/objectPropertyExcluder.js
Labels: ready

#52 #171767630 Add host link to chat html
  public/chat.html
  src/controllers/commentsController.js
  src/controllers/tripsController.js
  src/routes/api/chat.routes.js
  src/routes/api/index.js
  views/index.ejs
Labels: ready

#55 #170947468 Most traveled destinations
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/controllers/tripsController.js
  src/middlewares/validateTrip.js
  src/routes/api/accommodation.routes.js
  src/routes/api/trips.routes.js
  src/services/bookingService.js
  src/services/tripsService.js
  src/tests/editTripRequest.test.js
  src/tests/mostTraveledCentres.test.js
Labels: ready

#56 #171828036 View all accommodations
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/migrations/20200228101559-update-accommodations.js
  src/database/models/Accommodations.js
  src/routes/api/accommodation.routes.js
  src/services/accommodationService.js
  src/tests/allAccommodations.test.js
Labels: ready

#57 #171828179 Search accommodations
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/routes/api/accommodation.routes.js
  src/services/accommodationService.js
  src/tests/searchAccommodation.test.js
  src/tests/tripRequests.test.js
Labels: ready

#58 #171847100 View one accommodation
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/accommodation.js
  src/database/models/Accommodations.js
  src/routes/api/accommodation.routes.js
  src/tests/getOneAccom.test.js
Labels: ready

#59 Show notifications for posted comments
  public/index.html
  src/controllers/accommodation.js
  src/controllers/commentsController.js
  src/controllers/notification.js
  src/controllers/tripsController.js
  src/database/migrations/20200224160514-update-notifications-table.js
  src/database/migrations/20200311060335-create-acommodation-likes-and-unlikes.js
  src/database/models/acommodationlikesandunlikes.js
  src/tests/bookAccomondation.test.js
  src/tests/editTripRequest.test.js
  src/tests/notification.test.js
  src/tests/rejectTrip.test.js
Labels: ready

#61 #170947462 suppliers add accommodation facilities
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package.json
  src/database/migrations/20200218083837-update_users_table.js
  src/database/seeders/20200211104631-dummy-user.js
  src/middlewares/isTravelAdministrator.js
  src/validation/user.validation.js
Labels: ready

#62 chore(response): refactor response objects
  .DS_Store
  package-lock.json
  package.json
  public/index.html
  src/controllers/accommodation.js
  src/controllers/tripsController.js
  src/database/migrations/20200228101559-update-accommodations.js
  src/database/models/Accommodations.js
  src/index.js
  src/services/accommodationService.js
  src/tests/accommodations.rate.test.js
  src/tests/allAccommodations.test.js
  src/tests/getOneAccom.test.js
  src/tests/searchAccommodation.test.js
  src/tests/tripRequests.test.js
  src/utils/socket.js
Labels: ready

#63 #171927127 add some unit tests to hit our target of 96%
  src/database/seeders/20200226101607-dummy-trip-requests.js
  src/tests/editTripRequest.test.js
  src/tests/mock/editTripRequestMock.js
Labels: ready

#64 #171967419 Fix In-App notifications and get one trip request feature.
  public/index.html
  src/controllers/commentsController.js
  src/controllers/notification.js
  src/controllers/tripsController.js
  src/tests/tripRequests.test.js
Labels: ready
