Repository andela/octopus-bn-backend, pull requests merged in 2020-02, with the labels that each got.

#4 #170947426 Setup dotenv environment variables
  .env.example
  README.md
  package-lock.json
  src/index.js
Labels: feedback implemented, ready for review

#3 #170947423 integrates hound ci with badge in the repo
  .DS_Store
  .hound.yml
  README.md
Labels: ready for review

#2 #170947424 set up travis ci
  .travis.yml
  README.md
  package.json
Labels: ready for review

#5 #170947425 Setup unit testing
  .eslintrc.json
  package-lock.json
  package.json
  src/index.js
  src/test/server.test.js
Labels: ready for review

#9 #170947421 setup sequelize ORM
  .env.example
  .sequelizerc
  README.md
  package-lock.json
  package.json
  src/config/index.js
  src/database/config/config.js
  src/database/migrations/20200206093213-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20200206095927-dummy-user.js
Labels: ready for review

#8 #170947431 deploy base app on heroku
  README.md
  package.json
  procfile
Labels: ready for review

#19 #171178620 Create pull request template
  .github/pull-request.template.md
Labels: ready for review

#18 #171204743 setup multilingual access
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/index.js
  src/routes/api/welcome.js
Labels: ready for review

#14 #170947432 Integrate JSON web token
  README.md
  package.json
  src/test/jwtTokenizer.test.js
  src/test/mockData/jwtTokenizer.mock.js
  src/utils/jwtTokenizer.js
Labels: ready for review

#17 #170947434 user inputs validation
  .travis.yml
  package-lock.json
  package.json
  src/database/config/config.js
  src/database/migrations/20200206093213-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/userRoutes.js
  src/routes/api/users.js
  src/tests/jwtTokenizer.test.js
  src/tests/mockData/jwtTokenizer.mock.js
  src/tests/server.test.js
  src/tests/user.validation.test.js
  src/validation/user.validation.js
Labels: ready for review

#15 #170947433 Implement user registration
  .eslintrc.json
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/seeders/20200211104631-dummy-user.js
  src/routes/api/index.js
  src/routes/api/user.routes.js
  src/routes/api/welcome.js
  src/tests/mockData/user.mock.js
  src/tests/signup.test.js
  src/tests/user.validation.test.js
  src/utils/email.helper.js
Labels: ready for review

#16 #170947435 Build sign-in feature
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/config/config.js
  src/database/seeders/20200211104631-dummy-user.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/user.routes.js
  src/routes/api/users.js
  src/tests/jwtTokenizer.test.js
  src/tests/mock/jwtTokenizer.mock.js
  src/tests/mock/user.mock.js
  src/tests/server.test.js
  src/tests/signin.test.js
  src/tests/signup.test.js
  src/validation/user.validation.js
Labels: ready for review

#20 #170947438 User logout
  .github/PULL_REQUEST_TEMPLATE.md
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  src/config/passport.js
  src/controllers/userController.js
  src/database/models/index.js
  src/routes/api/index.js
  src/routes/api/user.routes.js
  src/routes/api/welcome.js
  src/tests/logout.test.js
  src/utils/isLoggedIn.js
  src/utils/profileCallback.js
Labels: ready for review

#22 #170947440 One way trip request
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/controllers/tripsController.js
  src/database/migrations/20200216110620-create-travel-requests.js
  src/database/models/travelRequests.js
  src/index.js
  src/middlewares/checkUser.js
  src/middlewares/tripRequestValidator.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/trips.routes.js
  src/tests/mock/facebookMock.js
  src/tests/mock/jwtTokenizer.mock.js
  src/tests/mock/tripRequestsMock.js
  src/tests/socialLogin.test.js
  src/tests/tripRequests.test.js
Labels: ready for review

#23 #170947439 Add profile settings
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/userController.js
  src/database/migrations/20200218162551-add-optional-cols-users.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/middlewares/checkUser.js
  src/routes/api/user.routes.js
  src/tests/XprofileSettings.test.js
  src/tests/mock/profileSettingsMock.js
  src/tests/signup.test.js
  src/utils/api-specifications.js
  src/utils/international.js
  src/validation/user.validation.js
Labels: ready for review

#21 #170947445 User role settings
  package.json
  src/controllers/userController.js
  src/database/migrations/20200206093213-create-users.js
  src/database/migrations/20200218083837-update_users_table.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/database/seeders/20200211104632-dummy-users.js
  src/routes/api/index.js
  src/routes/api/user.routes.js
  src/tests/XprofileSettings.test.js
  src/tests/mock/jwtTokenizer.mock.js
  src/tests/mock/user.mock.js
  src/tests/signin.test.js
  src/tests/signup.test.js
  src/tests/tripRequests.test.js
  src/utils/emailHelper.js
  src/utils/responses.js
  src/validation/user.validation.js
Labels: ready for review

#24 #170947437 Build password reset feature
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  package-lock.json
  package.json
  src/controllers/userController.js
  src/database/seeders/20200211104631-dummy-user.js
  src/routes/api/user.routes.js
  src/tests/mock/jwtTokenizer.mock.js
  src/tests/restPassword.test.js
  src/tests/tripRequests.test.js
  src/utils/emailHelper.js
  src/validation/user.validation.js
Labels: ready for review

#25 #170947441 return trip request
  src/controllers/tripsController.js
  src/database/migrations/20200216110620-create-travel-requests.js
  src/database/models/travelRequests.js
  src/database/seeders/20200211104631-dummy-user.js
  src/middlewares/tripRequestValidator.js
  src/routes/api/user.routes.js
  src/tests/mock/tripRequestsReturnMock.js.js
  src/tests/tripRequests.test.js
Labels: ready for review

#27 #171423803 refactoring trip requests messages and auth validation
  src/config/passport.js
  src/controllers/tripsController.js
  src/controllers/userController.js
  src/database/migrations/20200206093213-create-users.js
  src/database/migrations/20200222121846-create-update-users-table.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/database/seeders/20200211104632-dummy-users.js
  src/middlewares/checkUser.js
  src/middlewares/tripRequestDateValidator.js
  src/middlewares/tripRequestValidator.js
  src/routes/api/trips.routes.js
  src/tests/mock/facebookMock.js
  src/tests/mock/googleMock.js
  src/tests/mock/tripRequestsMock.js
  src/tests/mock/tripRequestsReturnMock.js.js
  src/tests/multiCityRequest.test.js
  src/tests/tripRequests.test.js
Labels: ready for review

#29 #171424328 Refactor multiCity trip request
  README.md
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/tripsController.js
  src/controllers/userController.js
  src/database/migrations/20200216110620-create-travel-requests.js
  src/database/migrations/20200216110621-update-travel-requests.js
  src/database/migrations/20200219165220-create-travel-requests.js
  src/database/models/travelRequests.js
  src/database/seeders/20200211104632-dummy-users.js
  src/middlewares/checkUser.js
  src/routes/api/trips.routes.js
  src/routes/api/user.routes.js
  src/tests/mock/multiCityMock.js
  src/tests/multiCityRequest.test.js
  src/utils/tripHelper.js
  src/validation/multiCity.validation.js
Labels: Finished

#28 #171423226 refactor i18n
  .DS_Store
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/userController.js
  src/database/seeders/20200211104631-dummy-user.js
  src/middlewares/checkUser.js
  src/middlewares/isProfileUpdated.js
  src/routes/api/trips.routes.js
  src/tests/XprofileSettings.test.js
  src/tests/mock/profileSettingsMock.js
  src/tests/signin.test.js
  src/utils/api-specifications.js
  src/utils/international.js
  src/validation/user.validation.js
Labels: ready for review

#30 #170947444 User view his/her trip requests
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/tripsController.js
  src/database/seeders/20200211104631-dummy-user.js
  src/middlewares/paramsValidator.js
  src/middlewares/tripRequestDateValidator.js
  src/middlewares/tripRequestValidator.js
  src/routes/api/trips.routes.js
  src/tests/multiCityRequest.test.js
  src/tests/tripRequests.test.js
  src/utils/pagination.js
Labels: ready for review

#32 #171424328 Avail pending requests
  locales/en.js
  locales/en.json
  locales/fr.js
  locales/fr.json
  src/controllers/tripsController.js
  src/controllers/userController.js
  src/database/migrations/20200206093213-create-users.js
  src/database/migrations/20200216110620-create-travel-requests.js
  src/database/models/travelRequests.js
  src/database/models/users.js
  src/database/seeders/20200211104631-dummy-user.js
  src/database/seeders/20200211104632-dummy-users.js
  src/middlewares/paramsValidator.js
  src/routes/api/trips.routes.js
  src/routes/api/user.routes.js
  src/services/tripsService.js
  src/tests/availRequests.test.js
  src/tests/mock/jwtTokenizer.mock.js
  src/tests/multiCityRequest.test.js
  src/tests/restPassword.test.js
  src/tests/signup.test.js
  src/utils/paginate.js
  src/validation/multiCity.validation.js
Labels: Finished

#31 #170947452 Add Search Functionality
  .eslintrc.json
  locales/en.js
  src/controllers/tripsController.js
  src/routes/api/trips.routes.js
  src/tests/search.test.js
Labels: ready for review
